runtime: python
env: flex # Especifica o ambiente flexível
entrypoint: gunicorn -b :$PORT app:app # Comando para iniciar o servidor

runtime_config:
  python_version: 3 # Ou 3.9, 3.8 etc., compatível com sua imagem base implícita

# Configurações opcionais de escalonamento, recursos, etc.
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10
