# app.yaml
# Configuração para Google App Engine - Ambiente Flexível com Dockerfile

# Indica ao App Engine para usar o Dockerfile na raiz do projeto
runtime: custom

# Ainda necessário para especificar o ambiente Flexível
env: flex

# REMOVA ou COMENTE a linha 'entrypoint', pois o comando é definido no Dockerfile (CMD)
# entrypoint: gunicorn -b :$PORT app:app

# REMOVA ou COMENTE a linha 'runtime_version' ou 'runtime_config',
# pois a versão do Python é definida na cláusula FROM do Dockerfile.
# runtime_version: '3.10'
# runtime_config:
#   python_version: 3

# --- Configurações Opcionais ---
# As configurações de escalonamento e recursos ainda são válidas aqui.
# Elas controlam a infraestrutura do App Engine, não o container em si.
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 3
#   cpu_utilization:
#     target_utilization: 0.7
# resources:
#   cpu: 1
#   memory_gb: 0.6
#   disk_size_gb: 10
# health_check: # Verificações de saúde ainda são configuradas aqui
#   enable_health_check: True
#   check_interval_sec: 30
#   timeout_sec: 4
#   unhealthy_threshold: 2
#   healthy_threshold: 2

